### ISSUE TITLE
chowning very slow on network drives

### ISSUE THREAD

**Issue by raphaelyancey** [m3adow/dockerfiles#3]
https://github.com/m3adow/dockerfiles/blob/eb44c792b98fd51b77732bc247929792ac9f9747/seafile/seafile-entrypoint.sh#L129

This line is **very** slow on large libraries (> 200GB) on a network drive (glusterfs).

Is it mandatory? Why in the first place?

Thank you very much.

**Comment by m3adow** [comment]
Hey,

I'm not 100% certain why I added this, but I remember having problems without it. I assume due to wrong permissions of data files.

You can try running the container with "run_only" appended. This should be much faster.

Does this help?

**Comment by raphaelyancey** [comment]
@m3adow It did, thanks!
